# Generated by Django 3.1.7 on 2021-03-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_for_transcript', '0002_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
